#!/usr/bin/env bash
# ============================================================
# scripts/live-e2e/setup.sh
#
# Brings up a disposable, repeatable live integration environment:
# a funded testnet deployer, freshly-deployed marketplace + launchpad
# contracts, a seeded collection/listing/auction/offer, and the full
# PostgreSQL + Redis + indexer + frontend stack wired to them.
#
# This is deliberately a *disposable testnet* strategy (not a local
# Soroban sandbox): it reuses the existing, already-idempotent deploy
# tooling in scripts/deploy/ instead of standing up a separate local
# validator, which keeps this environment behaviorally identical to
# what actually runs in production (real RPC, real ledger timing, real
# fee/resource limits) — the exact class of bug mocked E2E tests can't
# catch.
#
# Usage: ./scripts/live-e2e/setup.sh [--skip-deploy] [--dry-run] [--help]
#
# Flags:
#   --skip-deploy   Reuse contract IDs from a previous run
#                   (scripts/deploy/deployed_ids.env) instead of
#                   redeploying. Useful for iterating on tests quickly.
#   --dry-run       Print the steps that would run without doing them.
#   --help          Show this message and exit.
#
# Output:
#   scripts/live-e2e/.env.live-e2e   — resolved config for docker-compose
#                                       and the Playwright live suite.
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DEPLOY_DIR="$REPO_ROOT/scripts/deploy"
LIVE_ENV_FILE="$SCRIPT_DIR/.env.live-e2e"
COMPOSE_FILE="$REPO_ROOT/docker-compose.live-e2e.yml"

SKIP_DEPLOY=false
DRY_RUN=false

usage() {
  grep '^#' "$0" | grep -v '^#!/' | sed 's/^# \{0,1\}//'
}

for arg in "$@"; do
  case "$arg" in
    --skip-deploy) SKIP_DEPLOY=true ;;
    --dry-run) DRY_RUN=true ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: Unknown flag: $arg"; usage; exit 1 ;;
  esac
done

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ELCARE-HUB — Live Integration Environment Setup"
if $DRY_RUN; then echo "  (DRY RUN)"; fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

for cmd in docker jq curl; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: '$cmd' is required but not installed."
    exit 1
  fi
done

if ! docker compose version &>/dev/null; then
  echo "ERROR: 'docker compose' (v2 plugin) is required."
  exit 1
fi

# ── Step 1: deploy (or reuse) contracts ─────────────────────
if $SKIP_DEPLOY; then
  echo ""
  echo "Step 1/4  Skipping deploy — reusing $DEPLOY_DIR/deployed_ids.env"
  if [[ ! -f "$DEPLOY_DIR/deployed_ids.env" ]] && ! $DRY_RUN; then
    echo "ERROR: --skip-deploy was passed but deployed_ids.env doesn't exist yet."
    exit 1
  fi
else
  echo ""
  echo "Step 1/4  Deploying fresh contracts to testnet..."
  if $DRY_RUN; then
    echo "DRY RUN: Would run fund_account.sh, deploy_contract.sh, deploy_launchpad.sh"
  else
    "$DEPLOY_DIR/fund_account.sh"
    "$DEPLOY_DIR/deploy_contract.sh"
    "$DEPLOY_DIR/deploy_launchpad.sh"
  fi
fi

# ── Step 2: seed collections / listing / auction / offer ────
echo ""
echo "Step 2/4  Seeding test collection, listing, auction, and offer..."
if $DRY_RUN; then
  echo "DRY RUN: Would run $SCRIPT_DIR/seed.sh"
else
  "$SCRIPT_DIR/seed.sh"
fi

# ── Step 3: resolve config for docker-compose ────────────────
echo ""
echo "Step 3/4  Writing $LIVE_ENV_FILE ..."
if $DRY_RUN; then
  echo "DRY RUN: Would source deployed_ids.env + seed_ids.env and write $LIVE_ENV_FILE"
else
  # shellcheck disable=SC1091
  source "$DEPLOY_DIR/deployed_ids.env"
  # shellcheck disable=SC1091
  source "$DEPLOY_DIR/.env.deploy"
  # shellcheck disable=SC1091
  source "$SCRIPT_DIR/seed_ids.env"

  {
    echo "# ELCARE-HUB Live Integration Environment"
    echo "# Generated by scripts/live-e2e/setup.sh — do not commit."
    echo "MARKETPLACE_CONTRACT_ID=${MARKETPLACE_CONTRACT_ID}"
    echo "LAUNCHPAD_CONTRACT_ID=${LAUNCHPAD_CONTRACT_ID:-}"
    echo "STELLAR_NETWORK=${NETWORK}"
    echo "STELLAR_RPC_URL=${RPC_URL}"
    echo "STELLAR_HORIZON_URL=${HORIZON_URL}"
    echo "STELLAR_NETWORK_PASSPHRASE=Test SDF Network ; September 2015"
    echo "LIVE_E2E_SELLER_SECRET=${STELLAR_SECRET}"
    echo "LIVE_E2E_SELLER_PUBLIC=${STELLAR_PUBLIC}"
    # Pass every SEED_* / LIVE_E2E_BUYER_* value straight through so setup.sh
    # never has to be updated when seed.sh starts seeding something new.
    grep -E '^(SEED_|LIVE_E2E_BUYER_)' "$SCRIPT_DIR/seed_ids.env"
  } > "$LIVE_ENV_FILE"
  echo "  Written."
fi

# ── Step 4: bring up the stack ────────────────────────────────
echo ""
echo "Step 4/4  Starting PostgreSQL, Redis, indexer, and frontend..."
if $DRY_RUN; then
  echo "DRY RUN: Would run: docker compose -f $COMPOSE_FILE --env-file $LIVE_ENV_FILE up -d --wait"
else
  docker compose -f "$COMPOSE_FILE" --env-file "$LIVE_ENV_FILE" up -d --wait
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✓ Live environment ready."
echo "    Frontend : http://localhost:3100"
echo "    Indexer  : http://localhost:4100/health"
echo "  Run tests with:  npm run test:e2e:live --prefix frontend/elcarehub-app"
echo "  Tear down with:  ./scripts/live-e2e/teardown.sh"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
