/**
 * load-tests/fixtures/seed.ts
 *
 * Seeds the isolated load-test PostgreSQL + Redis environment with synthetic
 * fixtures generated by generate.ts.  Run after the Docker Compose stack is
 * healthy.
 *
 * Usage:
 *   DATABASE_URL="postgresql://ltuser:ltpass@localhost:5433/marketplace_lt" \
 *   REDIS_URL="redis://localhost:6380" \
 *   npx tsx load-tests/fixtures/seed.ts
 *
 * Environment overrides:
 *   SEED_LISTINGS    (default 2000)
 *   SEED_AUCTIONS    (default 500)
 *   SEED_OFFERS      (default 4000)
 *   SEED_EVENTS      (default 10000)
 *   SEED_COLLECTIONS (default 100)
 *   SEED_BATCH_SIZE  (default 500)  — rows per Prisma createMany call
 */

import { PrismaClient } from '@prisma/client';
import { createClient } from 'redis';
import { generateFixtures } from './generate.js';

const BATCH = parseInt(process.env.SEED_BATCH_SIZE ?? '500', 10);

const prisma = new PrismaClient({
  datasources: {
    db: { url: process.env.DATABASE_URL },
  },
  log: [{ level: 'warn', emit: 'stdout' }],
});

async function chunk<T>(items: T[], size: number, fn: (batch: T[]) => Promise<void>) {
  for (let i = 0; i < items.length; i += size) {
    await fn(items.slice(i, i + size));
  }
}

async function main() {
  const t0 = Date.now();

  console.log('[seed] Generating fixtures…');
  const fixtures = generateFixtures({
    seedListings:    parseInt(process.env.SEED_LISTINGS    ?? '2000',  10),
    seedAuctions:    parseInt(process.env.SEED_AUCTIONS    ?? '500',   10),
    seedOffers:      parseInt(process.env.SEED_OFFERS      ?? '4000',  10),
    seedEvents:      parseInt(process.env.SEED_EVENTS      ?? '10000', 10),
    seedCollections: parseInt(process.env.SEED_COLLECTIONS ?? '100',   10),
  });

  // ── SyncState ───────────────────────────────────────────────────────────────
  console.log('[seed] SyncState…');
  await prisma.syncState.upsert({
    where: { id: 1 },
    create: { id: 1, lastLedger: 1_000_000, lastLedgerHash: 'aabbccdd' },
    update: { lastLedger: 1_000_000 },
  });

  // ── TrackedContracts ────────────────────────────────────────────────────────
  console.log('[seed] TrackedContracts…');
  for (const tc of fixtures.trackedContracts) {
    await prisma.trackedContract.upsert({
      where: { contractId: tc.contractId },
      create: tc,
      update: { lastLedger: tc.lastLedger },
    });
  }

  // ── Collections ─────────────────────────────────────────────────────────────
  console.log(`[seed] Collections (${fixtures.collections.length})…`);
  await chunk(fixtures.collections, BATCH, (batch) =>
    prisma.collection.createMany({ data: batch, skipDuplicates: true }),
  );

  // ── Listings ─────────────────────────────────────────────────────────────────
  console.log(`[seed] Listings (${fixtures.listings.length})…`);
  await chunk(fixtures.listings, BATCH, (batch) =>
    prisma.listing.createMany({ data: batch as any, skipDuplicates: true }),
  );

  // ── Auctions ─────────────────────────────────────────────────────────────────
  console.log(`[seed] Auctions (${fixtures.auctions.length})…`);
  await chunk(fixtures.auctions, BATCH, (batch) =>
    prisma.auction.createMany({ data: batch as any, skipDuplicates: true }),
  );

  // ── Offers ────────────────────────────────────────────────────────────────────
  console.log(`[seed] Offers (${fixtures.offers.length})…`);
  await chunk(fixtures.offers, BATCH, (batch) =>
    prisma.offer.createMany({ data: batch as any, skipDuplicates: true }),
  );

  // ── Bids ──────────────────────────────────────────────────────────────────────
  console.log(`[seed] Bids (${fixtures.bids.length})…`);
  await chunk(fixtures.bids, BATCH, (batch) =>
    prisma.bid.createMany({ data: batch as any, skipDuplicates: true }),
  );

  // ── MarketplaceEvents ─────────────────────────────────────────────────────────
  console.log(`[seed] MarketplaceEvents (${fixtures.events.length})…`);
  await chunk(fixtures.events, BATCH, (batch) =>
    prisma.marketplaceEvent.createMany({ data: batch as any, skipDuplicates: true }),
  );

  // ── RoyaltyPayments ───────────────────────────────────────────────────────────
  console.log(`[seed] RoyaltyPayments (${fixtures.royaltyPayments.length})…`);
  await chunk(fixtures.royaltyPayments, BATCH, (batch) =>
    prisma.royaltyPayment.createMany({ data: batch as any, skipDuplicates: true }),
  );

  // ── PriceHistory ──────────────────────────────────────────────────────────────
  console.log(`[seed] PriceHistory (${fixtures.priceHistory.length})…`);
  await chunk(fixtures.priceHistory, BATCH, (batch) =>
    prisma.priceHistory.createMany({ data: batch as any, skipDuplicates: true }),
  );

  // ── Redis warm-up ─────────────────────────────────────────────────────────────
  // Pre-populate the 20 most-queried cache keys so early k6 requests observe
  // realistic cache-hit ratios rather than a cold-start artifact.
  console.log('[seed] Redis warm-up…');
  const redisUrl = process.env.REDIS_URL ?? 'redis://localhost:6380';
  const redis = createClient({ url: redisUrl });
  await redis.connect();

  // Cache the first page of listings
  const firstListings = await prisma.listing.findMany({
    take: 20,
    orderBy: { updatedAtLedger: 'desc' },
  });
  const ttl = 30;
  await redis.setEx(
    'cache:/listings?limit=20&offset=0',
    ttl,
    JSON.stringify(firstListings, (_k, v) => (typeof v === 'bigint' ? v.toString() : v)),
  );

  // Cache a stats snapshot
  const [totalListings, activeListings] = await Promise.all([
    prisma.listing.count(),
    prisma.listing.count({ where: { status: 'Active' } }),
  ]);
  await redis.setEx('cache:/stats', ttl, JSON.stringify({ totalListings, activeListings }));

  await redis.disconnect();

  const elapsed = ((Date.now() - t0) / 1000).toFixed(1);
  console.log(`\n[seed] Done in ${elapsed}s`);
  console.log(`  listings:     ${fixtures.listings.length}`);
  console.log(`  auctions:     ${fixtures.auctions.length}`);
  console.log(`  offers:       ${fixtures.offers.length}`);
  console.log(`  bids:         ${fixtures.bids.length}`);
  console.log(`  events:       ${fixtures.events.length}`);
  console.log(`  collections:  ${fixtures.collections.length}`);
  console.log(`  priceHistory: ${fixtures.priceHistory.length}`);
  console.log(`  royalties:    ${fixtures.royaltyPayments.length}`);
}

main()
  .catch((err) => {
    console.error('[seed] Fatal error:', err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
